DROP TABLE IF EXISTS T_SYS_USER;
DROP TABLE IF EXISTS T_API_USER;
DROP TABLE IF EXISTS T_API_USER_PERM;

CREATE TABLE T_SYS_USER (
  ID         BIGINT IDENTITY,
  EMAIL      VARCHAR(60),
  LOGIN_NAME VARCHAR(30) NOT NULL UNIQUE,
  NAME       VARCHAR(20),
  PASSWORD   VARCHAR(60),
  OTHER      VARCHAR(512),
  PRIMARY KEY (ID)
);

CREATE TABLE T_API_USER (
  ID         BIGINT IDENTITY,
  USER_NAME  VARCHAR(30),
  PASSWORD   VARCHAR(60),
  PRIMARY KEY (ID)
);

CREATE TABLE T_API_USER_PERM (
  ID            BIGINT IDENTITY,
  USER_NAME     VARCHAR(30),
  DS_TYPE       VARCHAR(20),
  TABLE_NAME    VARCHAR(20),
  OPT_PERM      VARCHAR(20),
  PRIMARY KEY (ID)
);



