DROP TABLE IF EXISTS T_SYS_USER;
DROP TABLE IF EXISTS T_API_USER;

CREATE TABLE T_SYS_USER (
  ID         BIGINT IDENTITY,
  EMAIL      VARCHAR(255),
  LOGIN_NAME VARCHAR(255) NOT NULL UNIQUE,
  NAME       VARCHAR(255),
  PASSWORD   VARCHAR(255),
  OTHER      VARCHAR(512),
  PRIMARY KEY (ID)
);

CREATE TABLE T_API_USER (
  ID         BIGINT IDENTITY,
  USER_NAME      VARCHAR(255),
  PASSWORD   VARCHAR(255),
  PRIMARY KEY (ID)
);



